version: "3.9"

services:
    app:
        # php コンテナ
        build:
            context: .
            dockerfile: ./app/Dockerfile
        volumes:
            - ./src/:/app
    web:
        # nginx コンテナ
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        ports:
            - 8080:80
        depends_on:
            - app
        volumes:
            - ./src/:/app
    db:
        # mysql コンテナ
        build:
            context: .
            dockerfile: ./docker/db/Dockerfile
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            TZ: 'Asia/Tokyo'
        volumes:
            - mysql-volume:/var/lib/mysql
    phpmyadmin:
        # Docker Hubからイメージをダウンロード
        image: phpmyadmin/phpmyadmin
        # コンテナと他のサービスを繋げる
        links:
            - db
        ports:
            - 8888:80
        # セッション情報をボリュームに設定して永続化
        volumes:
            - ./docker/phpmyadmin/sessions:/sessions

volumes:
    mysql-volume:
