version: "3.9"

services:
    # laravel.test:
    #     build:
    #         context: ./vendor/laravel/sail/runtimes/7.4
    #         #   dockerfile: Dockerfile
    #         # args:
    #         #     WWWGROUP: "${WWWGROUP}"
    #     image: sail-7.4/app
    #     # extra_hosts:
    #     #     - "host.docker.internal:host-gateway"
    #     # ports:
    #     #     - "${APP_PORT:-80}:88"
    #     volumes:
    #         - ".:/var/www/html"
    #     # networks:
    #     #     - sail
    #     depends_on:
    #         - mysql
    app:
        # php コンテナ
        build:
            context: .
            dockerfile: ./app/Dockerfile
        volumes:
            - ./src/:/app
    web:
        # nginx コンテナ
        build:
            context: .
            dockerfile: ./docker/web/Dockerfile
        ports:
            - 8080:80
        depends_on:
            - app
        volumes:
            - ./src/:/app
    db:
        # mysql コンテナ
        build:
            context: .
            dockerfile: ./docker/db/Dockerfile
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            TZ: 'Asia/Tokyo'
        volumes:
            - mysql-volume:/var/lib/mysql
    phpmyadmin:
        # Docker Hubからイメージをダウンロード
        image: phpmyadmin/phpmyadmin
        # コンテナと他のサービスを繋げる
        links:
            - db
        ports:
            - 8888:80
        # セッション情報をボリュームに設定して永続化
        volumes:
            - ./docker/phpmyadmin/sessions:/sessions

volumes:
    mysql-volume:
